name: ci

on:
  push:
    branches: ["feat/**", "chore/**", "fix/**", "d2-training-setup"]
  pull_request:
    branches: ["d2-training-setup", "main"]
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
    inputs:
      run_comprehensive:
        description: "Run comprehensive testing (includes d2_quick and extended nightly)"
        required: false
        default: "false"
        type: boolean
      alpha_values:
        description: 'Alpha values for testing (comma-separated, e.g., "0.05,0.1,0.5")'
        required: false
        default: "0.1"
        type: string
      client_count:
        description: "Number of clients for manual runs"
        required: false
        default: "5"
        type: string
      round_count:
        description: "Number of rounds for manual runs"
        required: false
        default: "10"
        type: string

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install deps
        run: |
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint & unit tests
        env:
          D2_EXTENDED_METRICS: "1"
        run: |
          if command -v flake8 >/dev/null 2>&1; then flake8 ; fi
          pytest -q

      - name: Smoke FL (only on feature branches)
        if: startsWith(github.ref, 'refs/heads/feat/')
        env:
          D2_EXTENDED_METRICS: "1"
        run: |
          python scripts/run_fl.py --clients 2 --rounds 3 --alpha 0.1 --preset smoke_feat_iid --partition_strategy iid --leakage_safe
          python scripts/run_fl.py --clients 2 --rounds 3 --alpha 0.1 --preset smoke_feat_dirichlet --partition_strategy dirichlet --leakage_safe

      - name: Upload smoke artifacts
        if: startsWith(github.ref, 'refs/heads/feat/')
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts-${{ github.sha }}
          path: |
            runs/**/metrics.csv
            runs/**/client_*_metrics.csv
            runs/**/client_metrics_plot.png
            runs/**/server_metrics_plot.png

  d2_quick:
    if: github.ref == 'refs/heads/d2-training-setup' || (github.event_name == 'pull_request' && github.base_ref == 'd2-training-setup') || (github.event_name == 'workflow_dispatch' && github.event.inputs.run_comprehensive == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - run: |
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Benign quick
        env:
          D2_EXTENDED_METRICS: "1"
        run: python scripts/run_fl.py --clients 5 --rounds 10 --alpha 0.1 --preset d2_quick_benign --partition_strategy dirichlet --leakage_safe
      - name: Adversarial quick
        env:
          D2_EXTENDED_METRICS: "1"
        run: python scripts/run_fl.py --clients 5 --rounds 10 --alpha 0.1 --preset d2_quick_adv --partition_strategy dirichlet --adversary_mode label_flip --leakage_safe

      - name: Schema/metric checks
        run: python scripts/ci_checks.py --runs_dir runs

      - uses: actions/upload-artifact@v4
        with:
          name: d2-quick-artifacts-${{ github.sha }}
          path: runs/**

  nightly_full:
    runs-on: ubuntu-latest
    timeout-minutes: 240 # 4 hours
    strategy:
      fail-fast: false
      matrix:
        alpha: [0.05, 0.1, 0.5]
        scenario: ["benign", "adversarial"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - name: Install dependencies with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: |
            pip install -r requirements.txt
            if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Full sweep (10c×30r) - ${{ matrix.scenario }}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 200
          max_attempts: 2
          retry_on: error
          command: |
            export D2_EXTENDED_METRICS="1"
            if [ "${{ matrix.scenario }}" = "benign" ]; then
              python scripts/run_fl.py --clients 10 --rounds 30 --alpha ${{ matrix.alpha }} --preset d2_full_${{ matrix.alpha }}_benign --partition_strategy dirichlet --leakage_safe
            else
              python scripts/run_fl.py --clients 10 --rounds 30 --alpha ${{ matrix.alpha }} --preset d2_full_${{ matrix.alpha }}_adv --partition_strategy dirichlet --adversary_mode label_flip --leakage_safe
            fi

      - name: Validate results
        run: python scripts/ci_checks.py --runs_dir runs

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: d2-full-${{ matrix.alpha }}-${{ matrix.scenario }}-${{ github.sha }}
          path: runs/**
          retention-days: 30

  nightly_notify:
    needs: nightly_full
    runs-on: ubuntu-latest
    if: always() && needs.nightly_full.result == 'failure'
    steps:
      - name: Log nightly failure (issues disabled)
        run: |
          echo "🚨 Nightly CI Pipeline Failed"
          echo "Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Failed at: $(date)"
          echo "Check the workflow run for details"

  manual_testing:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: ["benign", "adversarial"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Parse alpha values and run tests
        env:
          D2_EXTENDED_METRICS: "1"
        run: |
          IFS=',' read -ra ALPHAS <<< "${{ github.event.inputs.alpha_values }}"
          for alpha in "${ALPHAS[@]}"; do
            alpha=$(echo "$alpha" | xargs)  # trim whitespace
            if [ "${{ matrix.scenario }}" = "benign" ]; then
              python scripts/run_fl.py \
                --clients ${{ github.event.inputs.client_count }} \
                --rounds ${{ github.event.inputs.round_count }} \
                --alpha "$alpha" \
                --preset "manual_${alpha}_benign" \
                --partition_strategy dirichlet \
                --leakage_safe
            else
              python scripts/run_fl.py \
                --clients ${{ github.event.inputs.client_count }} \
                --rounds ${{ github.event.inputs.round_count }} \
                --alpha "$alpha" \
                --preset "manual_${alpha}_adv" \
                --partition_strategy dirichlet \
                --adversary_mode label_flip \
                --leakage_safe
            fi
          done

      - name: Validate results
        run: python scripts/ci_checks.py --runs_dir runs

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: manual-test-${{ matrix.scenario }}-${{ github.sha }}
          path: runs/**
          retention-days: 7

  release_on_tag:
    if: startsWith(github.ref, 'refs/tags/D2-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create GitHub Release
        run: |
          gh release create "${GITHUB_REF_NAME}" --notes-from-tag --title "Deliverable 2 – ${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Optionally upload run artifacts if present
        run: |
          set -e
          FILES=$(ls runs/**/client_metrics_plot.png runs/**/server_metrics_plot.png runs/**/metrics.csv 2>/dev/null || true)
          if [ -n "$FILES" ]; then
            gh release upload "${GITHUB_REF_NAME}" $FILES
          else
            echo "No run artifacts found; skipping upload."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
